### ISSUE TITLE
restful daemon for integration with other language ?

### ISSUE THREAD

**Issue by aderumier** [btrplace/scheduler#177]
Hi,

I'm looking to test btrplace scheduler with proxmox hypervisor for vm placements. Currently proxmox is perl5 (yep :p) , so it's not easy to integrate it with brtplace.

I would like to known if a working restful server is available somewhere ?(something like playd, but the build process from doc don't seem to work, maybe it's not maintened ?)

Basically, I would like to inject host/vm ressources configuration, some constraint rules  and get the results.

(I have never coded with java, sorry. )

**Comment by fhermeni** [comment]
Hi Alexandre

Regarding playd, the compilation went fine on my machine but I was not able to launch it as stated in my documentation. I did not use that code for a long time, I'll check.

I am not aware of any restful frontend for the scheduler publicly available. It is not very hard to do but I have to find spare time. The thing is : as the json serialisation is already here, it is mostly a packaging and presentation issue so something that may have particular requirements quite fast.

**Comment by aderumier** [comment]
ok thanks !

**Comment by fhermeni** [comment]
Won't do. Too specialised
