### ISSUE TITLE
Shortest solution isn't chosen

### ISSUE THREAD

**Issue by MichaelDrogalis** [btrplace/scheduler#87]
Made a JSON reproduction [here](https://gist.github.com/MichaelDrogalis/db97db8beec5778b4d2e).

This case uses 4 nodes with 5 VMs, and sets capacity constraints on each of the nodes. The VM layout is set with `running` and `ready` before the planner begins. The planner, I think, unnecessarily moves VMs from their original placement, hence not taking the fastest solution.

**Comment by fhermeni** [comment]
Hi
Thanks for the report.
There is indeed a bug with the objective computation.

If you want a workaround, use the repair mode (http://www.btrplace.org/apidocs/index.html?org/btrplace/scheduler/choco/Parameters.html). It will prevent some VMs to move and lead to the optimal solution.

**Comment by MichaelDrogalis** [comment]
Thanks @fhermeni!!
